BUG: clear LivePVTableModel._poll_thread.data after stopping thread
The existing code would occassionally cause this error when closing
a tab containing a LivePVTableModel:

Traceback (most recent call last):
  File "/afs/slac.stanford.edu/u/cd/devagr/src/superscore/superscore/widgets/views.py", line 1021, in run
    self._update_data(pv_name)
  File "/afs/slac.stanford.edu/u/cd/devagr/src/superscore/superscore/widgets/views.py", line 1008, in _update_data
    if not isinstance(val, Exception) and self.data[pv_name] != val:
KeyError: 'VAC:GUNB:TEST1'

This error appears to be caused by LivePVTableModel.stop_polling
clearing _PVPollThread's data before calling its stop method, causing
the thread to be able to run for another cycle and try to access its
now-empty data. Calling stop() and then waiting before clearing the
data seems to prevent the error.